apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      env: auth
  template:
    metadata:
      labels:
        env: auth
    spec:
      containers:
      - name: auth-app
        image: energy1971/auth-service:latest
        # auth-service:latest
        env:
        # Define the environment variable
        - name: PG_HOST              # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: auth-cm             # The ConfigMap this value comes from.
              key: PG_HOST              # The key to fetch.
        - name: PG_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: auth-cm
              key: PG_DB_NAME
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: PG_USER
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: PG_PASSWORD
        ports:
        - name: auth-port
          containerPort: 8000     
